### ISSUE TITLE
how to understand "near_two" in this nice project

### ISSUE THREAD

**Issue by seek66** [DRCL-USC/Hector_Simulation#26]
想问下为啥用“near_two(c_row[j])”这个条件标记要消除的变量呢，为啥是数值接近2呢
![11](https://github.com/user-attachments/assets/84ef1684-fc4d-4f73-b5ae-7eaa56e2809c)

**Comment by seek66** [comment]
excuse me，I would like to ask why the condition "near_two (c_row [j])" is used to mark the variable to be eliminated, and why is the value close to 2

**Comment by junhengl** [comment]
Hi, 
The original Cheetah source code used near_one as the condition to do elimination, and that indicates the force limit constraint for each leg. However, on Hector implementation, we have additional constraints that may have 1s in constraints other than just force limits. for example,  https://github.com/DRCL-USC/Hector_Simulation/blob/5e0ca67ce4ca5b1879391438c6f54c7224ec4da1/Hector_ROS_Simulation/hector_control/ConvexMPC/SolverMPC.cpp#L524 
To work around it, we use near_two to check when the force limit constraint appears in order to do eliminations. In the F_control matrix, you can find the corresponding lines that have 2 in them, indicating the force limit constraint to do the elimination checking. 
https://github.com/DRCL-USC/Hector_Simulation/blob/5e0ca67ce4ca5b1879391438c6f54c7224ec4da1/Hector_ROS_Simulation/hector_control/ConvexMPC/SolverMPC.cpp#L528

**Comment by seek66** [comment]
thank you very very very very much！！&nbsp;


黎健亮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junheng ***@***.***&gt;; 
发送时间: 2024年8月2日(星期五) 凌晨5:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DRCL-USC/Hector_Simulation] how to understand &quot;near_two&quot; in this nice project (Issue #26)














 
Hi,
 The original Cheetah source code used near_one as the condition to do elimination, and that indicates the force limit constraint for each leg. However, on Hector implementation, we have additional constraints that may have 1s in constraints other than just force limits. for example,  https://github.com/DRCL-USC/Hector_Simulation/blob/5e0ca67ce4ca5b1879391438c6f54c7224ec4da1/Hector_ROS_Simulation/hector_control/ConvexMPC/SolverMPC.cpp#L524
 To work around it, we use near_two to check when the force limit constraint appears in order to do eliminations. In the F_control matrix, you can find the corresponding lines that have 2 in them, indicating the force limit constraint to do the elimination checking.
 https://github.com/DRCL-USC/Hector_Simulation/blob/5e0ca67ce4ca5b1879391438c6f54c7224ec4da1/Hector_ROS_Simulation/hector_control/ConvexMPC/SolverMPC.cpp#L528

**Comment by seek66** [comment]
> Hi, The original Cheetah source code used near_one as the condition to do elimination, and that indicates the force limit constraint for each leg. However, on Hector implementation, we have additional constraints that may have 1s in constraints other than just force limits. for example,
> 
> https://github.com/DRCL-USC/Hector_Simulation/blob/5e0ca67ce4ca5b1879391438c6f54c7224ec4da1/Hector_ROS_Simulation/hector_control/ConvexMPC/SolverMPC.cpp#L524
> 
> 
> To work around it, we use near_two to check when the force limit constraint appears in order to do eliminations. In the F_control matrix, you can find the corresponding lines that have 2 in them, indicating the force limit constraint to do the elimination checking.
> https://github.com/DRCL-USC/Hector_Simulation/blob/5e0ca67ce4ca5b1879391438c6f54c7224ec4da1/Hector_ROS_Simulation/hector_control/ConvexMPC/SolverMPC.cpp#L528

thank you  very very very much!!
